[build]
rustflags = ["-Ctarget-cpu=native"]

[target.x86_64-unknown-linux-musl]
rustflags = [
  "-C", "target-cpu=x86-64",
  "-C", "target-feature=-avx,-avx2,-avx512f,-avx512vl,-avx512dq,-avx512bw,-avx512ifma,-avx512vbmi,-vaes,-vpclmulqdq"
]
